# Matrix market file to load
input_matrix = finan512.mtx
# input_matrix = ./finan512/finan512.mtx

# Overlap extension
overlap = 2

# Coarse space type: none | pou | algebraic_geneo | algebraic_msgfem
coarse_type = algebraic_msgfem

# Partition of unity configuration
[pou]
type = distance
shrink = 1

# Combined preconditioner mode
[combined_preconditioner]
mode = multiplicative

# Fine level (Schwarz) preconditioner
[schwarz]
type = restricted

[schwarz.subdomain_solver]
type = umfpack

[galerkin]
type = umfpack

# GenEO / MsGFEM coarse space eigensolver configuration
# For MsGFEM: constraint_evp = lagrange_multiplier | alternating
[coarsespace]
constraint_evp = lagrange_multiplier

[coarsespace.eigensolver]
type      = Spectra
nev       = 16
nev_max   = 32
shift     = -100
maxit     = 1000
tolerance = 1e-5
threshold = -2

[coarsespace.eigensolver.solver]
type = umfpack

# Coarse solver configuration
[coarse_solver]
type = umfpack

# Outer solver
[solver]
type      = restartedgmressolver
reduction = 1e-6
maxit     = 1000
restart   = 100
verbose   = 2
