# Visualization
visualise = true
view_report = true
filename = pdelab_example

# Grid configuration
gridsize = 1000
refine = 0
overlap = 4
debug_rank = 13

# Coarse space configuration
# domain:         full | ring
# constraint:     none | harmonic
# constraint_evp: lagrange_multiplier | alternating  (only for constraint = harmonic)
# ring_extension: from_ring | from_boundary          (only for domain = ring)
#
# NOTE: The 'alternating' approach does produce correct results for non-symmetric problems.
#
[coarsespace]
domain = full
constraint = harmonic
constraint_evp = lagrange_multiplier
ring_extension = from_boundary

# Partition of unity configuration
[pou]
type = distance # distance
shrink = 2

# Combined preconditioner mode
[combined_preconditioner]
mode = multiplicative

# Fine level (Schwarz) preconditioner
[schwarz]
type = restricted

[schwarz.subdomain_solver]
type = umfpack_metis

# Coarse solver configuration
[coarse_solver]
type = umfpack

[coarsespace.eigensolver]
type      = Spectra
nev       = 32
nev_max   = 256
# ncv       = 48
shift     = -0.001
maxit     = 1000
tolerance = 1e-8
threshold = 2

# Outer solver
[solver]
type      = restartedgmressolver # cgsolver
reduction = 1e-8
maxit     = 100
restart   = 50
verbose   = 4
