# Visualization
visualise = true
view_report = true
filename = pdelab_example

# Grid configuration
gridsize_per_rank = 16
refine = 0
overlap = 4
debug_rank = 2

# Coarse space configuration
[coarsespace]
type = geneo # geneo_ring

# Partition of unity configuration
[pou]
type = distance # distance
shrink = 2

# Combined preconditioner mode
[combined_preconditioner]
mode = multiplicative

# Fine level (Schwarz) preconditioner
[schwarz]
type = restricted

[schwarz.subdomain_solver]
type = umfpack

# Coarse solver configuration
[coarse_solver]
type = umfpack

[coarse_space.eigensolver]
type      = trl
nev       = 16
# ncv       = 32
shift     = -0.001
maxit     = 1000
tolerance = 1e-12
#threshold = 0.05

# Outer solver
[solver]
type      = restartedgmressolver # cgsolver
reduction = 1e-8
maxit     = 100
restart   = 50
verbose   = 4
